apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kavita
  namespace: media-stack
spec:
  interval: 20m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-app-template-repo
        namespace: flux-system
  values:
    - kind: Secret
      name: kavita-values
