apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cardavregex
  namespace: default
spec:
  replacePathRegex:
    regex: ^/\.well-known/(?:carddav|caldav)
    replacement: /dav/
