apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dendrite/repository.yaml
  - ./dendrite/release.yaml
namespace: productivity-stack
configurations:
  - kustomizeconfig.yaml
secretGenerator:
  - name: dendrite-values
    files:
      - values.yaml=./dendrite/values.sops.yaml
