### Para poder usar Telegraf en OKE se tiene que desactivar SELinux con
### https://docs.fedoraproject.org/en-US/quick-docs/selinux-changing-states-and-modes/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: telegraf
  namespace: management-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: telegraf-ds
      version: 1.1.36
      sourceRef:
        kind: HelmRepository
        name: influx-repo
        namespace: management-stack
  valuesFrom:
    - kind: Secret
      name: telegraf-values
