metrics:
  health:
    enabled: false
    service_address: http://:8888
    threshold: 5000
  internal:
    enabled: true
    collect_memstats: false
## Default values.yaml for Telegraf
## This is a YAML-formatted file.
## ref: https://hub.docker.com/r/library/telegraf/tags/
image:
  repo: telegraf
  tag: 1.30-alpine
  pullPolicy: IfNotPresent
## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 2Gi
    cpu: 200m
## Pod annotations
podAnnotations: {}
## Pod labels
podLabels: {}
## Configure args passed to Telegraf containers
args: []
## The name of a secret in the same kubernetes namespace which contains values to
## be added to the environment (must be manually created)
## This can be useful for auth tokens, etc.
# envFromSecret: "telegraf-tokens"
rbac:
  # Specifies whether RBAC resources should be created
  create: true
  # Create only for the release namespace or cluster wide (Role vs ClusterRole)
  clusterWide: true
  # Rules for the created rule
  rules:
    - apiGroups:
        - ""
        - networking.k8s.io
        - apps
      resources:
        - bindings
        - componentstatuses
        - configmaps
        - endpoints
        - events
        - limitranges
        - namespaces
        - nodes
        - persistentvolumeclaims
        - persistentvolumes
        - pods
        - podtemplates
        - replicationcontrollers
        - resourcequotas
        - secrets
        - serviceaccounts
        - services
        - mutatingwebhookconfigurations
        - validatingwebhookconfigurations
        - customresourcedefinitions
        - apiservices
        - controllerrevisions
        - daemonsets
        - deployments
        - replicasets
        - statefulsets
        - tokenreviews
        - localsubjectaccessreviews
        - selfsubjectaccessreviews
        - selfsubjectrulesreviews
        - subjectaccessreviews
        - horizontalpodautoscalers
        - cronjobs
        - jobs
        - certificatesigningrequests
        - leases
        - endpointslices
        - events
        - flowschemas
        - prioritylevelconfigurations
        - ingressclasses
        - ingresses
        - networkpolicies
        - runtimeclasses
        - poddisruptionbudgets
        - podsecuritypolicies
        - clusterrolebindings
        - clusterroles
        - rolebindings
        - roles
        - priorityclasses
        - csidrivers
        - csinodes
        - csistoragecapacities
        - storageclasses
        - volumeattachments
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
      resources:
        - ingresses/status
        - ingresses
      verbs:
        - get
        - list
        - watch
    - nonResourceURLs:
        - /metrics
      verbs:
        - get
# serviceAccount:
#   # Specifies whether a ServiceAccount should be created
#   create: true
## Environment
env:
  - ENC[AES256_GCM,data:adNc2qZP6gBVH0BEcONgI6wXPqaTBNN85m1deQpfx1kn1/hl3doFXOMFYz8a5vUB,iv:8S0XJ00nOpwISZhg7hYpnHnZOvkAhTr/Wggrw3gXxMQ=,tag:GD6rcEUMXJsOK6w/jV8Xnw==,type:comment]
  - name: ENC[AES256_GCM,data:NqvVAxgLbyQ=,iv:tQ/NNVNmMXo7sYkqQ6NIVsLc3BQ2P8fYn+iZYPMs2hU=,tag:hUzpczvu8sUogABWH87a3w==,type:str]
    valueFrom:
      fieldRef:
        fieldPath: ENC[AES256_GCM,data:Ba/f1RMEWT0IW/y65A==,iv:RoaxWO2PXZ6kg/9nF3viRMssUwywYc1GIzhF8xzpUzM=,tag:+heg1kETvrZ7ATEmI/rQqA==,type:str]
  - ENC[AES256_GCM,data:k4HHqwUS8p2izWppAfswzhiGDBZt12rVF7evf65yiLw58l82hEnHYj+NrevGMn1P/RM8P7tQLHItQVOtF1TARk/KvstedRx6od4=,iv:ukxgM/Z8vneUlC4THxjG2+YkK6Nj8kstPJmGZkKMeXg=,tag:cC7qmoKHvj5qUSl088EX8Q==,type:comment]
  - ENC[AES256_GCM,data:aYVL7k3Ay9LptB1k86MT93JsTNo8Ws/5rZLR9KINzGE4gF40YOZ0qUZTQuy3LIVZiToHn0pa,iv:ubDYN3tnaXpqd78Ki9g32LftY+GdU8G1g0jxCDGkF9U=,tag:RrtePNH1JB8xryRqXov7uQ==,type:comment]
  - ENC[AES256_GCM,data:NmjXRgkd8JyNAZRaiwe7yc0KmNNOxvvR934fhqWu,iv:WZ08X46om62ff87ngNm22KsVtkf3/uSpYNCofO2WFys=,tag:3fyY1ULm3x8nCOhMmNWkpA==,type:comment]
  - name: ENC[AES256_GCM,data:uzZJpJeO,iv:LVLXvUoH/jzGH3WKWEDkPDM6a1uc1S9mMoKHmLrBnyE=,tag:KeugeFtOwRkc/z1Dt44WKQ==,type:str]
    valueFrom:
      fieldRef:
        fieldPath: ENC[AES256_GCM,data:Q5JIAJhC0BaPuSWRLA==,iv:prIWGZ3nTU9bpLm7MiVi5vw9/mXI8rqUDZzg9doa4To=,tag:Hkrfd6Dlcavau6MbN/Td5A==,type:str]
  - ENC[AES256_GCM,data:9T93Wb2vwatnB6eVnep984G/FzpWL+FiQA7IxCQNtOd7Pe6oS5b+155hk0pD6843KU9td2CI5rzB5VyTi7pf+60=,iv:R5ENhJL3TXwb+P8dPslO/UaKifqGnD8ohdbMPN/DhII=,tag:PDY1cRceRnGvsWLiC+kkDg==,type:comment]
  - ENC[AES256_GCM,data:fOjwwSJL5cwUTpTPnARp/sOg0yR7pQ60XutWN4prdEgNOi9/IZwutxG0uTzrhBOFjB4XWNqN1Peozalbo8g4uNbHgWA=,iv:YYjMZxnOxF3tNo1n8VdqwARIEVh4w0FZG1lJW7G8i4M=,tag:Bkvc/pD0HKl48dzxEPiXyQ==,type:comment]
  - ENC[AES256_GCM,data:m5+l7HmtzNS/CYdSoTQDmwu6Qz00sQQhVMFmPMb2uScVszwLE4BNNsm41TkH1PsNGftwStfhr1NSRiY3VRHb57pbrR7Xtq4kknYkbGoncp18b5Y=,iv:QGUxbC8Ns22orLRFwmkBdlqihNj3mIwp4Rpe/cB+Mxk=,tag:PgJnWFwUbDlqk9eE3KGJIQ==,type:comment]
  - name: ENC[AES256_GCM,data:Bk7cqEOOsNj1,iv:0n0Y/y3fyQHnD7cV9zKOIaDuuZPTNsgd4rLiHfNn4U0=,tag:lNgCD1Fqc5Q7kBLhCZYSrA==,type:str]
    value: ENC[AES256_GCM,data:pR+DiR3HAb+GiO/g,iv:soDejmyinw/jqzTSJ4oi3Rpuh0tHeRV0raBMnlQRpgQ=,tag:Kv6VLtty89nfhvILT7dZqQ==,type:str]
  - ENC[AES256_GCM,data:lJkISmeR1SYdTHztkZB41C1j25jwz5JhmZH5Fu7GsO1Oa2/c+GcKuoho,iv:8ky+SRYLWXnQDETLYwyLUY/LN8y1lvWVpnBJEkmMHnA=,tag:1aKDzrKx2Cz5cq8jBl/BpA==,type:comment]
  - name: ENC[AES256_GCM,data:lUCUb8z7wsA=,iv:jbMTWNAnqx37LyIRSnE0htMohBCu+4ifoLCqkADqGFY=,tag:bz80M0R2nad6+DukmIG2Qw==,type:str]
    value: ENC[AES256_GCM,data:flIE+FUtwpMrc7A=,iv:GmiHCHoRXmDsz1tJD2Jsf3fywNsVzmhy0qC7WvUDQxY=,tag:osev9piP4s8D5Ly2nBilOg==,type:str]
  - name: ENC[AES256_GCM,data:/FVdnz4I7JTbx2e/4J4z84k=,iv:R0vneDG5G17a3Wk6sI+uGmzeihCss8IJY7+9FuZKKJ0=,tag:HOnkxJZtInhqHz3+leicOw==,type:str]
    value: ENC[AES256_GCM,data:F+UjqDk4GQ==,iv:T3B/9ldjTxu3BMS8XwAPg/1fWlE57W3GPaJc25O4qiA=,tag:TRBZHFstzahVW1kAa9W+Bg==,type:str]
## Add custom volumes and mounts
# volumes:
# - name: telegraf-output-influxdb2
#   configMap:
#     name: "telegraf-output-influxdb2"
# mountPoints:
# - name: telegraf-output-influxdb2
#   mountPath: /etc/telegraf/conf.d
#   subPath: influxdb2.conf
## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
## If the DaemonSet should run on the host's network namespace
## hostNetwork: true
## If using hostNetwork=true, set dnsPolicy to ClusterFirstWithHostNet
## ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#
## dnsPolicy: ClusterFirstWithHostNet
## If using dnsPolicy=None, set dnsConfig
## ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
## dnsConfig:
##   nameservers:
##     - 1.2.3.4
##   searches:
##     - ns1.svc.cluster-domain.example
##     - my.dns.search.suffix
##   options:
##     - name: ndots
##       value: "2"
##     - name: edns0
# Specify the pod's SecurityContext, including the OS user and group to run the pod
# podSecurityContext:
# privileged: true
override_config:
  toml: null
  # Provide a literal TOML config
  # toml: |+
  #   [global_tags]
  #     foo = "bar"
  #   [agent]
  #     interval = "10s"
  #   [[inputs.mem]]
  #   [[outputs.influxdb_v2]]
  #     urls           = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  #     bucket         = "data"
  #     organization   = "OurCompany"
  #     token          = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
## Exposed telegraf configuration
## ref: https://docs.influxdata.com/telegraf/v1.13/administration/configuration/
config:
  # global_tags:
  #   cluster: "mycluster"
  agent:
    interval: 10s
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: 0s
    flush_interval: 10s
    flush_jitter: 0s
    precision: ""
    debug: false
    quiet: false
    logfile: ""
    hostname: ENC[AES256_GCM,data:QnxasU8X92hm,iv:GMzi9JPk8N8AImPgR/Bx6WKdoKX5hbrJOlWyvT6GN5E=,tag:2wDKi5G6myhEsV21eH1JZA==,type:str]
    omit_hostname: false
  processors:
    - enum:
        mapping:
          field: status
          dest: status_code
          value_mappings:
            healthy: 1
            problem: 2
            critical: 3
  inputs:
    - diskio: {}
    - kernel: {}
    - mem: {}
    - net: {}
    - processes: {}
    - swap: {}
    - system: {}
    - cpu:
        # percpu: true
        totalcpu: true
        # collect_cpu_time: false
        report_active: false
    - disk:
        ignore_fs:
          - tmpfs
          - devtmpfs
          - devfs
          - iso9660
          - overlay
          - aufs
          - squashfs
    # - kube_inventory:
    #     url: ""
    #     namespace: ""
    #     insecure_skip_verify: true
    #     resource_exclude:
    #       - "secrets"
    - kubernetes:
        url: https://$HOSTIP:10250
        bearer_token: /var/run/secrets/kubernetes.io/serviceaccount/token
        insecure_skip_verify: true
  outputs:
    - influxdb_v2:
        urls:
          - ENC[AES256_GCM,data:Ukas0ZOgVBwW+G9QJSNVZ4VZohKS28bZ2XF7On0jq8tfkeGueXAAe/66tySHABbF7E6BUftLfmoYIs66,iv:QUNe+qWlHVJcg7F5hKzNQ7HFvjSPJxEyh4VH3L3LboM=,tag:9V+1QbmdeFWMeMBrFv6vlA==,type:str]
        token: ENC[AES256_GCM,data:H8KxcA3UGIe2erWsLphgu/QtGVf55/0zztmICQNR1x8XpYv6ziNYWu9AbwUF+MsuWzaq7/EcysrwbxWPf4qVnas9k0KNUOyWHiHAKvSdzFN2FPIHtXt7hg==,iv:OoGroUs37Dvgnco4gx93+WS4mtaylU8s9pSwLtTDdJk=,tag:GjEXoBCUQava3YXJA3OZPQ==,type:str]
        organization: ENC[AES256_GCM,data:Rg82BRxruBRWmA==,iv:0bN1rjfhhZ30WvON8KlRPC/lhl/k/Rki54/tu/o5KDs=,tag:wY7IOEULx10H5cT0e6EcPg==,type:str]
        bucket: ENC[AES256_GCM,data:9uCesHMeCXIAxw==,iv:MIz0UI9nM/Lk/O/cptvKRRXAtSMrC6Br1MmML9yq37U=,tag:dh6ge68KmVaLqgOR3BXh4w==,type:str]
        insecure_skip_verify: ENC[AES256_GCM,data:Yvt+tLU=,iv:OXe7jJ5/9yQhwzoK3LgRKIDCE4I1mkwBLADq5mI6ARU=,tag:9rCTiJca5uMsho8r02sACQ==,type:bool]
  monitor_self: false
  docker_endpoint: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1u9xhf474aapqtea5myafnd6asdwv8nldgu2gefxcvdl2869zddwspsdqu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTktCdkNqWGdPK2wvWWdT
        R2c2blNOZkdFZmFVMlJTSlJHYUxSLy9UUmxJCi9hbUtIUzBqYjkwN0FaME1XN1ha
        b2xSS25qcG8xWDhobUVqb25Wa1FxcmsKLS0tIFcySUtUaVpLZ3Q1cUVQeXF1Zjkx
        YWZLSUVXQWw0VWZ4c0ZGazNNcnFvNHcKBoLVdZ/mJQiCcODOcKkmiOjnK+mHoBhS
        Wao/e/3/m5d+z3B1SggAews89WQJK/l1R89jUnBjb9mTYZ8Vmblk+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T18:32:05Z"
  mac: ENC[AES256_GCM,data:oRfPjR5CBJMxrKpbAgMaQNYQPrdMlWhVVJJWS5KkhkDdaZbF0+Oa5b0eIrK9tVijDbZbMEkPCILwhFjiCTwHYNhuSXpOpO3lddTDZBpIhNmUeCWmuw/VeBrHY5lZG9CCzG4t+bCSZ0XgIHP/12kPsGIN9zO0PYX0YhITWJlIYAU=,iv:9po1nwx1gbLFFI5kV2AsER0HDqI3SHtz2WaY7du1ih0=,tag:u0btnb0LGe+NGd3UXOQioQ==,type:str]
  pgp: []
  encrypted_regex: ^(id|secret|password|extraEnv|env|encryption_key|data|stringData|host|db|influxdb_v2)|(external-dns.alpha.kubernetes.io.*|kubernetes.io/ingress.class.*)$
  version: 3.9.1
