apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sr-online
  labels:
    name: sr-online
  namespace: management-stack
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jf.homenets.xyz
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: jf.homenets.xyz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: sr
                port:
                  number: 8096
