apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./n8n/release.yaml
  - ./n8n/repository.yaml
  - ./directus/release.yaml
namespace: development
configurations:
  - kustomizeconfig.yaml
secretGenerator:
  - name: n8n-values
    files:
      - values.yaml=./n8n/values.sops.yaml
  - name: directus-values
    files:
      - values.yaml=./directus/values.sops.yaml
