# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json
controllers:
    main:
        strategy: Recreate
        revisionHistoryLimit: 2
        containers:
            main:
                probes:
                    liveness:
                        enabled: false
                    readiness:
                        enabled: false
                    startup:
                        enabled: false
                image:
                    repository: ccarney16/pterodactyl-panel
                    tag: v1.11.2
                    pullPolicy: IfNotPresent
                env:
                    - name: ENC[AES256_GCM,data:bwnfX6zpuw==,iv:haKXvO177tfSmMwJ+9+wanS42LQID5EHwWI8MqbMthQ=,tag:or2csaMMq/kQM1a8CJa2lQ==,type:str]
                      value: ENC[AES256_GCM,data:9/1J2Nw/tdE15RrHWWkvkwzQdUNX/gNWegmii1VBh7o=,iv:X9F9SuYw9cFjgUeMkL+wxCr7mALdAqT+jkht0JQVy8I=,tag:QNqyP4XqJ4iMnzQqtq6BhA==,type:str]
                    - name: ENC[AES256_GCM,data:g95NVRK+Mk/j2Ip/,iv:uAozNoO7NXAxlSyOPL+/PN+PLGJI7j0+B37MI6tHZuQ=,tag:8K90bMkeK8caVc2sbsrjFQ==,type:str]
                      value: ENC[AES256_GCM,data:yJ9p7L2ZXD7zGIuR,iv:W3zP+M5BsMPihf1QyFI0ylZ7uh0/ZtZHe/hwIqcpa8A=,tag:w85RQODN/Ld5APm69Y70Qw==,type:str]
                    - name: ENC[AES256_GCM,data:tNF2DkJYzwrdiH/zUlXAr/zP,iv:gadFLxZrViMFsvRGgVkJ6QSvLClHt6vs+hiM4TVP38M=,tag:HwUYLOv7XtZ/BAe8lZFE9Q==,type:str]
                      value: ENC[AES256_GCM,data:YHAeEdjkHK+6DV2o8nQB3TuZqxwL,iv:0/VkhF7EqQz2Qw4troPXYY6vRmBaZR3j3XmxhL/PZ34=,tag:8S1lPT+pS0zyXj0t3hAR7Q==,type:str]
                    - name: ENC[AES256_GCM,data:ec70PPq8NYaU,iv:gHeA8cXfdgr9MvUAKa/cjLmulNh/a8vHWvQbJ1r7Oxo=,tag:Vb0Uk5rByCuBBNQCXur2IA==,type:str]
                      value: ENC[AES256_GCM,data:ctYoC1kt6aEL4wef7imAPw2ePw5Row==,iv:xm+k9ztBSUYWQhORssR5494wlq4uQPo5rjPtqKVw384=,tag:7/6+6sgEEi76S1JANecYqg==,type:str]
                    - name: ENC[AES256_GCM,data:xRykH8sM5+ncycE=,iv:V79F1pewBEZz0pxvHVEuxB7kcKy3H0X+JziLpEIKUsI=,tag:KirenCAzDmgvVQf9n+Alpw==,type:str]
                      value: ENC[AES256_GCM,data:dV67Pg==,iv:elHyMfsz3k+H3UwVqOaKCj1J35CGSH1SxjGE4TiViBw=,tag:0mCDU3O/KT7TuSB6gD4TFQ==,type:str]
                    - name: ENC[AES256_GCM,data:k9kWyyeG1Mcu,iv:pUX9N5Vm3wKjWgRQmLBU9tlPKkhN4NgyVZFBkJjVgLw=,tag:baO+4K2lySkkgoIV1V+EOQ==,type:str]
                      value: ENC[AES256_GCM,data:XDjOpStFr0Rgt2VK5qU=,iv:nV99+GGvkRsQgdElXRNs3VJPFUSwqPRhCozMm5dNbP8=,tag:yExHVv1a/gbJXfWBhX2zOA==,type:str]
                    - name: ENC[AES256_GCM,data:bf/A678Faex6,iv:BMmGhIBSDmh+/b4LQjIXSoSAzFIkwt0ny5qEnHvJ6PQ=,tag:5tk5y5Zc//HLmd6kd4EUxw==,type:str]
                      value: ENC[AES256_GCM,data:wFfY,iv:6+CmDMyHwlPlJYLi1a1/yXqvM+/VCOyuvroRVWlypqY=,tag:OmhvFY4VB1aR3q1GdPyXhg==,type:str]
                    - name: ENC[AES256_GCM,data:wmBPMTGqfK6SO0JTnw==,iv:EEoRaIFllpuM3oX8M/bIfgmxBKE7/VoX0z0ojtlN7Mg=,tag:ZhmoGB1rOOYnPcAcKuDSiw==,type:str]
                      value: ENC[AES256_GCM,data:ZwffgZoA8QsoVME=,iv:qBTqivCuJVFdOxkuoRrC/idyiRfm55lm55FugcDBdCY=,tag:oiioqQ26QbY7/GgRT72eow==,type:str]
                    - name: ENC[AES256_GCM,data:uqlWXE9dliuhjyh4QA==,iv:COmEAY4NLPrYi+JtJFLz9sAti0NB8KA9tCw2rP2zQAk=,tag:qvyBmyY0PqmG79qsQ/TxAw==,type:str]
                      value: ENC[AES256_GCM,data:qplDXxyF1H2TS0suD/6XMQ==,iv:AF2o7o+76o4x70QewaIX0MNmPzo5rb9p9IuvBHC6MSU=,tag:cakRtPlMvPDuvyCy9rzTkQ==,type:str]
                    - name: ENC[AES256_GCM,data:Oj54p2LoFB2fOsa7c0zg,iv:KQz9Rp3Z7kI2CQpRDFdGeIyb6uykB3xcAeU+fDknHjg=,tag:6SoW0nyqcfNd35G3h9KFfg==,type:str]
                      value: ENC[AES256_GCM,data:7K9f,iv:gqovYvicgRAEC6AERmNpKvAYeddmuvUWE5noYm5k9ew=,tag:OUQQ/eHcnk3aURibb8g5kw==,type:str]
                    - name: ENC[AES256_GCM,data:V5kohuN0TQ==,iv:aSMXeHjGN+j4Frk55JRI0WXCJ52sPfphPQjm9RCq8i8=,tag:PyjpVICMs3weQFaprLeh9w==,type:str]
                      value: ENC[AES256_GCM,data:qwGFc5ln0KF7PZayKBkNRNvxyc0fg/VejFi0/63LWb/qjV/XBM9WvO4vK5a98N4CvN47,iv:7dv6hWvT+YTIMynCn0HTW/XhJGCWrXpo/+PyxV9dG9w=,tag:T/pFEDPNfiFL5rdQCZuLjQ==,type:str]
                    - name: ENC[AES256_GCM,data:CPlmdzK1OQ==,iv:DlDSo601leq7ebnzv+hSSHkD2/6cwWoMLHTlLONnQGk=,tag:KIZMnmX0iPlSCrofnmYR+w==,type:str]
                      value: ENC[AES256_GCM,data:40D4QNv3FPmITA==,iv:LAfnH79iNUTn1OyXfCt53oDRHT5uz3o/7Pn7b2j2M0Y=,tag:NTBk7jfslom1fGz3+vrmAw==,type:str]
                    - name: ENC[AES256_GCM,data:UkeGxyiZd2b8uu6JdIoWOqcgpDA=,iv:58MBJEwPWAka5pem4BgJhsTSHuCnkeTvcriOWSH4XlA=,tag:zthqynEsQu8JDqhT873rqQ==,type:str]
                      value: ENC[AES256_GCM,data:Qq7kPMc=,iv:Nbc5evdJyjdlMl5xfwo442AJqg71QbrlHLGEVASybpo=,tag:XuEiay7BhMNclRxyJ6EOqA==,type:str]
                    - name: ENC[AES256_GCM,data:GMzt9QGStx7i7vKz,iv:SHroxQRWxSOlIA/LPtj2gwuE4J4By9SmLNix3nBVeaA=,tag:yIf9ipc1kgOV0K8GwQ/VSA==,type:str]
                      value: ENC[AES256_GCM,data:Y/P0L1A=,iv:InSAPQZEnud0Q/RZKfiAQL1lgspgBOH4FnTIuhfMm4Q=,tag:N/bZ8Dm5yC8cJSCDXkm0Uw==,type:str]
                    - name: ENC[AES256_GCM,data:Z4ef0Mz3BD2CKkyYCQY=,iv:3eqZdKMBngpjn4/AicZD7yzDEvJQ+C+q3TZhZ93z0wU=,tag:DuX27ZwHei1rl2j8QsMg/w==,type:str]
                      value: ENC[AES256_GCM,data:Y/P0L1A=,iv:InSAPQZEnud0Q/RZKfiAQL1lgspgBOH4FnTIuhfMm4Q=,tag:N/bZ8Dm5yC8cJSCDXkm0Uw==,type:str]
                    - name: ENC[AES256_GCM,data:MQKy+CvA8jXbIqqF,iv:KGuEm+Q/Q/gYhMFnc/y2kuFjQNLrCktQrKxQh32V+Pk=,tag:5Vx8GFloenEu8iLQTOtkXA==,type:str]
                      value: ENC[AES256_GCM,data:Y/P0L1A=,iv:InSAPQZEnud0Q/RZKfiAQL1lgspgBOH4FnTIuhfMm4Q=,tag:N/bZ8Dm5yC8cJSCDXkm0Uw==,type:str]
                    - name: ENC[AES256_GCM,data:JT8Hcr7G3i5DBQ==,iv:34nmLCV1J/z4zLGk5uhiMMzDwlgG1jKI56OTWJiL274=,tag:ibOjvql0Ddh2EAMfpsVEtA==,type:str]
                      value: ENC[AES256_GCM,data:PGoRIKrHZth7FA7vpHUnFGEHjnF229MjZdOTlW2HPSvHvWUBdJej316i1GVENFoew2aLFytKQDu8glcH79ex1Ae9SQ==,iv:Tj3wtK2HfZxfG1KS7td4QZt9Pog63MoJ5l8T215km2Y=,tag:AeR69WtQUXwinkcPLfGADA==,type:str]
                    - name: ENC[AES256_GCM,data:LSb9PpIzFwrHh+Q=,iv:MXeUrc/2rhdGDMRdS1Wf9wU3t7ePITMPVHbq0PjUxoQ=,tag:aHbTSPjshTwSEqMGjEmPug==,type:str]
                      value: ENC[AES256_GCM,data:CEIj5mFUttG+0uhzfE6Fcg==,iv:JGZamTYshAL6A4J9CYXePtkTmDHpZRrwZxpiLOg/0oM=,tag:ob8wXKBH/xP0GKeHr+5Kdg==,type:str]
                    - name: ENC[AES256_GCM,data:pajpmXKYzQ==,iv:Q/931laaF8ESPrTogyH+1MS0NK4Vrm36jVGR79vaSEY=,tag:7rVxEy7v5UA5UziqPWrl+Q==,type:str]
                      value: ENC[AES256_GCM,data:eYJJZQ7rqPtd0IubtezKrV7vE2v29PdIY/jJ6yw+n0n1teV87P+PXA623QJPy//VsQ5NaE0=,iv:j7K2znVEyH+sVawcF03L3PwtiS9dEbaMVMxupp8IZSU=,tag:FvniGnC0DJVBWxSH48glxg==,type:str]
                    - name: ENC[AES256_GCM,data:VyLQlDSO+2+3tlc4idxF,iv:6Q3po/59l/yDFABrnn6Mc5bEm6BaNuJSp2vIlUKxWJk=,tag:688EkBOTztK1q43AdWlxlA==,type:str]
                      value: ENC[AES256_GCM,data:fg==,iv:u2wUE7XxvwaWmBTOXxAbrI/HFhGIosKXyGDgebHaf4g=,tag:xWo7kd09jUY70ZKZB3bQbA==,type:str]
                      #ENC[AES256_GCM,data:OXl1fgpTdz7mASzIfKOWmChrJ1HmFwGwWAbFuJuKs22JW4BQv2g=,iv:m9KaYkt6HQOIECcQEFtWQXUtGTDYGQAGC5HG//fNCzc=,tag:UW2nDII4YHZfu97Z6r3Flw==,type:comment]
                    - name: ENC[AES256_GCM,data:Bxexv4/EvXoeIr+rTbmBltU=,iv:4UgWWD9qF0ls+sxvMHabeYkoZalbaliUHPL75lYWzO8=,tag:2I6UbhoOe84PG+E23InAhg==,type:str]
                      value: ENC[AES256_GCM,data:2S8=,iv:SdvNAeSxRw5bBvZQhxc+T8lDIvyhOZwf2SmGues81Hk=,tag:kH2O+XLpYcmAo+3AyNi4Ug==,type:str]
                      #ENC[AES256_GCM,data:dkru2JJ41kuPBTNa7/dTC68ypr0g25sY,iv:uxyUfK9avifx/LtvAR31bMxFNELl6XSNYTP/Oi0aJgg=,tag:CKLRAq6EpxJLkZLZiFDCPw==,type:comment]
                    - name: ENC[AES256_GCM,data:6Da8wXml1ySX0KyKYcoGVYkg,iv:R/ckE/sEU8LT51dS+p5b56reu8Pc+KJ35FehGYmbQiM=,tag:rub85Jl5/21kf76Eg3T2nw==,type:str]
                      value: ENC[AES256_GCM,data:l3Y9bKlJb7SffizD,iv:t6/V+kE9p/XfckXGshE77+z6yK/srJ7cD4Zp2edYsHw=,tag:2NZbxA22CN8ttcwLwo2Ylg==,type:str]
                    - name: ENC[AES256_GCM,data:nrtLjG93+AnDAsEjefMhZjQ=,iv:1/EtZPoCekqOMXsUtH+HLZ09lFuuDXt/hWjceWvMML4=,tag:Neuxf2RnuGZS5bys6UKlEg==,type:str]
                      value: ENC[AES256_GCM,data:ZSufBCdzoWCGlWDj/dcnNPoH3cFoSoWuPgtAO7qkoWoN1NZ6+oEWbA==,iv:5YH5A4ddKNo7tX1TSUT7CyCFRuNVkSaMg/jKOHWJyQk=,tag:rhCdEK0nNDBLquVL+7MVtQ==,type:str]
                    - name: ENC[AES256_GCM,data:jXs5IGe40HDfVVf0tAidX+xF7VC1,iv:ds206Bh36yd7lrp4rYjKvNM3hYE/K4lnAMuWaVHncqc=,tag:0HrQ2hs3lFy1kgS3BvBahA==,type:str]
                      value: ENC[AES256_GCM,data:vehZdkldi2nH2kwfR0HMZIxe5KxPtZxuFCvR8Iv0ygKlhOcGhQv8l076RkU=,iv:/plSQ9AUV/K7aSmR1A1yOXQzd2sFao2feyZIYD49YIs=,tag:lgsoNR5BL7EdCdVpmhZcXA==,type:str]
                    - name: ENC[AES256_GCM,data:C8t4eBawj8660EPWF9gBP7xc,iv:14tcZC66qAowFOB1R4hfKDLvNMTwyvsS6Cuz3dGbF68=,tag:Q23aS0AtqiR1qcYLELEsAQ==,type:str]
                      value: ENC[AES256_GCM,data:dfUWmyICN1cUAl4WyYS4eqvG1A==,iv:PGHNI5EqwGpxsiHhswFsbmW0iHAhuBmQEh+bzqaWUyk=,tag:AKutByhGLnPrcmgXyJ6d+g==,type:str]
                    - name: ENC[AES256_GCM,data:RVA38DsI8o4bFQow,iv:v2TvRxh55Wn+wPX0G6oB6S2xL0RAlClbI7rZdch1xl8=,tag:4bHZyYBrbbEQ3oKzHy2kJg==,type:str]
                      value: ENC[AES256_GCM,data:vVr1nKTCRyaG1WxXGNbj/9PIeEd0JNM7naxuJDW1wQh6uQfW5DbXQjCPtdkafIaW5XgP9twk4bd+dBmmBijBai0F+my7vg==,iv:ADtJRvyr1QDzjR0fX0M4bNE6T1C4ZsvosNoN4oN2szs=,tag:xFAtjGqhPEf1VfKoUioJ0w==,type:str]
                    - name: ENC[AES256_GCM,data:RwDDU+NMjz5+8Sd7OyuKIty7I3Rr/gbqbKtm,iv:W7y5T/1gyGXjXqY6VR/64CGaSLLVgdjrU5JwWXLYjFU=,tag:rskcpM/tvOAqHeMUf/lW/g==,type:str]
                      value: ENC[AES256_GCM,data:JKk1sw==,iv:zDwIg6dtM8Fk1F+zc3n0TEU+4M1SbFBjyu96wphJmNo=,tag:zLqY/R5ySKPCHUhYW4/AsA==,type:str]
                      #ENC[AES256_GCM,data:oBWL9GDJ3RokVpZxqQ7VOOd1hUPGz8hDtr/YNVXHcKWQQ50=,iv:lfc45tBoLvGvLFh5GZTTzffD34gouH7INKlLK5Ezl7Y=,tag:QPLthqCo+vkuBscNXNLl0w==,type:comment]
                      #ENC[AES256_GCM,data:CzLSZZhzF7zJuNeiNY2R6XPMqV3fEVV7KymTFyLIFUdiJETEoA==,iv:h1DxGEPGRHN+b/lY7SPT5Q1Hq1VDP4ib0SPbQbOogZY=,tag:+FAbvDEZhtl030LJtDnuSg==,type:comment]
service:
    main:
        controller: main
        ports:
            http:
                port: 80
ingress:
    main:
        enabled: true
        annotations:
            external-dns.alpha.kubernetes.io/cloudflare-proxied: ENC[AES256_GCM,data:AFHVrg==,iv:RI5TVAgQ6hvvY4KkexwKyBrJtZWGqbsb1fuBL1uDD+c=,tag:K0eILUE+1VFYdsCdaoR7AA==,type:str]
            external-dns.alpha.kubernetes.io/enabled: ENC[AES256_GCM,data:0PZS5g==,iv:Wu25vsi8c3GjKxFBl8K1e0pKBeC7mNLw9LiWEvgfkAA=,tag:/CL7IlPqFoMxnYMt0jdEhQ==,type:str]
            kubernetes.io/ingress.class: ENC[AES256_GCM,data:704NTUSxvw==,iv:Kkn9Z+acv4gzCeYep/iEQKF3CrhR1v+FDkao66MEf/A=,tag:k1enrze23Rsw3k2YQ0C9TA==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:fl7W1ELiYSQteHxFSzeFwrZmcSJajS81,iv:xv/5ldyA3YdwXUWkm5HTRp11RDysuckAIMx+Wj37ERw=,tag:noOzTZScM/vmY9NO92Y8Pw==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:aw==,iv:5TKFqQt8tEE0ErfxW4zXWSY96oEPJZV04S/DCB2nEBs=,tag:P+I58sCrvqJBxf+fC0EtaA==,type:str]
                  pathType: ENC[AES256_GCM,data:WoWHU0vo,iv:L10d5sWhZr8vRttDIcqnXOLlU0bbW2MFDl6YjOYwsPk=,tag:lp9qljPiFdF8J7dCwoCk7g==,type:str]
                  service:
                    identifier: ENC[AES256_GCM,data:mPMNFg==,iv:/m2CQzUk4whdaWuopx+NEGpECQou1yQb0IrmPu0EtVg=,tag:MYRxNr8YTtYYVBo6VfVHcA==,type:str]
                    port: ENC[AES256_GCM,data:FAOAOw==,iv:XtXt4uWh6vjbFtd166jpRvZP72Mdj3z2uSQtd4hKxhk=,tag:KC2UMHyl9HYvNoFJZ2ZwEQ==,type:str]
persistence:
    data:
        enabled: ENC[AES256_GCM,data:XtUFMw==,iv:GF9p3EwE0vSK4tQgdGlcJbJgcLkEQSbdSZ0LOSsTEgw=,tag:envql9hLVBRTXLWFMabXkw==,type:bool]
        size: ENC[AES256_GCM,data:HHgliw==,iv:kihFlJLGWNNBso9IUHz5WPYpEg4KiMLGeeruzev40yY=,tag:bFrWVj2GBh/BIzZ4eRSNtQ==,type:str]
        type: ENC[AES256_GCM,data:RoCxv0dmNKGhZUC3lAH0UL99DV0A,iv:I9AgkjyIEo1+/8CDiwb67Q1Q9V7N1BpLTiSTJm6v+5Y=,tag:UWk2VbWtuQn2T1y0k1kJrA==,type:str]
        storageClass: ENC[AES256_GCM,data:jievy5stXsHKiQ==,iv:WXIyumXWQLdt2EfW5OGiw4LXv2ITsO6d7ZhDsBqIboo=,tag:MQZOXUAlq/TWDqHA3EuB0g==,type:str]
        accessMode: ENC[AES256_GCM,data:3UUJp8dnJA5bNvVy/g==,iv:I6pRFCnPPind2Fyy2CBFJtW+Fz9LHNm3fXB2hH4aeuY=,tag:7jeUi3XBQbwyVrLYRQljfA==,type:str]
    logs:
        enabled: true
        type: emptyDir
        globalMounts:
            - path: /app/storage/logs
    nginx:
        enabled: true
        size: 4Mi
        type: persistentVolumeClaim
        storageClass: nfs-client
        accessMode: ReadWriteOnce
        globalMounts:
            - path: /etc/nginx/conf.d/
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u9xhf474aapqtea5myafnd6asdwv8nldgu2gefxcvdl2869zddwspsdqu6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaTQvY25RUmE4SWdrTGU2
            OFVuZlBpOURqQUQ2blJZQ00yZzhQa3FaclNZCkFCTmRUYndnUzFWdHpaWndZNmR3
            cjMraXVnOGtqakhKbGJKZE1UbllCRW8KLS0tIDB2NTM3OEZwTzNDam4vNE5ETHFH
            bFZjYlZsRE9Dd2ZoYjdsUU9CSmYwREUK/1hNfxEyZBO+wZryz50u5CQf9ch1rMDL
            LLVr2KdzmcQmQPL/LOkaCN+ATH+KL39iWwaanDfMN30y8dVg1u/uyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T11:56:49Z"
    mac: ENC[AES256_GCM,data:6GNAW5S1ETH2hb3kpDS3S/ffJMz0Iqr8ejh4ZXjluxbhs6ZuqGLafzVq/NqdumpK6iUXaW2nosTpJcq01xaQDHNnRcbBbdObih68KLz9OYSLmMCWswqeWGbCuXJ8jiBB/FwxFzSPwF826yfVOhifppUcfU/p7RD/BAJNxiHAFvw=,iv:QQiKBW6vpKvQiq30ZNIGNK71osZDleg0kPsav4udBL8=,tag:ELL6USh4MnmxQesTTvcQVA==,type:str]
    pgp: []
    encrypted_regex: ^(id|secret|password|extraEnv|env|encryption_key|data|stringData|host|db|influxdb_v2|wildcardHost|clientId|clientSecret)|(external-dns.alpha.kubernetes.io.*|kubernetes.io/ingress.class.*)$
    version: 3.9.1
