# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json
controllers:
    main:
        strategy: Recreate
        revisionHistoryLimit: 2
        containers:
            main:
                probes:
                    liveness:
                        enabled: false
                    readiness:
                        enabled: false
                    startup:
                        enabled: false
                image:
                    repository: ghcr.io/pterodactyl/panel
                    tag: v1.11.10
                    pullPolicy: IfNotPresent
                env:
                    - name: ENC[AES256_GCM,data:gbqshGKZHQ==,iv:1UgPLfYb8Vgm/IUkvt935OcSiEkG8glMTV1ePbgRR3M=,tag:EswYBJ1cTD3q1C1FGMuJxg==,type:str]
                      value: ENC[AES256_GCM,data:05vhFpg7jKwelP1nGSxffOL5cLPlLnF/iaj/8XgPUh8=,iv:ODRh4eVXyoNy+ql2tDHbMxzhF8uk+2aNUrFloBAdptI=,tag:qa4/1Iv6uTf4wIFX3LwDfg==,type:str]
                    - name: ENC[AES256_GCM,data:g2uCTh8hWLYDsRGi,iv:xfbatWTp/frpqGpnG4pfkusEdCe4zXBXbFGjk71D+08=,tag:OXqGWf8GCD9UYrjGQG5K8g==,type:str]
                      value: ENC[AES256_GCM,data:iSYSMS81ZHYjQeGK,iv:K0Ael2NmyTTWoLmo/bGEOKQiMWkQEQNWp0VojJPABhk=,tag:1jUrnIQEATFvInAVCu3IkQ==,type:str]
                    - name: ENC[AES256_GCM,data:KUfn99t+57dkJxHt+ajxAcG5,iv:TpWpzTMpwH7HRTnL0bY8Bu5GAQyDE3/K9f87H7TimRs=,tag:mNvNpBnBiVDgC2gLuVgYnw==,type:str]
                      value: ENC[AES256_GCM,data:fwoNG1W+k4ryXCSrEW8nqs+Kaf6D,iv:MRPvX6joii/uLMXZBq2ppKPB58S0ERd90TVNUhAkOWg=,tag:1X0PxsJqRLyBeguocJ6myw==,type:str]
                    - name: ENC[AES256_GCM,data:OmqRv5YgR5Qd,iv:dfPNcHoYwVuUWAcSOUVYmzpPbrV4yhHsIb4Y5ozdJMM=,tag:KB1ndeDlNAyVle4zd5hEfA==,type:str]
                      value: ENC[AES256_GCM,data:o9f1KuGEaqzF6nYpHkWmrgI+5lntLA==,iv:kh0NQwDGUb724WR92JMnLqXvyxw7Td7ZFV8Nrj2VO3k=,tag:81ip2n10L+8GSuULjJO1Ug==,type:str]
                    - name: ENC[AES256_GCM,data:8mvzwbMui8nf/Ow=,iv:0g8ME7xzWAii1J1OPsrH6M2hn89Ec25Uuy0nRw6Um4o=,tag:rK+WGdOHx9IeUcv4WjNrug==,type:str]
                      value: ENC[AES256_GCM,data:cyqdzg==,iv:CKalb+90mQXM0+gtUFBCo3eXcrK97OY8xJCarAMJ8/U=,tag:xjEaJfb+mZRIqcG65ZbWIg==,type:str]
                    - name: ENC[AES256_GCM,data:kyiJEn8JD1MG,iv:PqkPnr9yPlAPyZ/7TyS0ratC5fUprEeqGQptui+AMt8=,tag:Pcg3F3/qqPhISPYM+ANaTw==,type:str]
                      value: ENC[AES256_GCM,data:0M4LlWLDGPtpmWI5sa0=,iv:EW3xbKSbfn+/DN8CFFT3bpxIZ3BCgFLGU3m66z93vlA=,tag:sGyDiP9QGSpV8EmvMI168g==,type:str]
                    - name: ENC[AES256_GCM,data:8iU+Tr56qhxp,iv:y6357L0yZBq1N4DLYY0fSNCCNPe/S+yaXG8gmP9KVa0=,tag:IqZmqWYY1NUFdkIvMe3xXA==,type:str]
                      value: ENC[AES256_GCM,data:HnCj,iv:NPrC3vOUGjwpJdFBkHjjbCF2s52ZI7DcLnuhOD1DaQE=,tag:tQzCrrRir8w2ondk022+eA==,type:str]
                    - name: ENC[AES256_GCM,data:mN+AyuElB35GXRODOQ==,iv:iLfEFbR8iXXiJB+g89IvNha2rndOzsxjYXyxjOkGVtI=,tag:pubXNev3O/qLSJZxdvPvGw==,type:str]
                      value: ENC[AES256_GCM,data:AMwfobKi29j8uBI=,iv:iGx1GHQIbHcYL3+xlEA02sIbIlNkaIV75TUFSeaX8+M=,tag:waHrZJNz1IQ6kbF3Lbru+g==,type:str]
                    - name: ENC[AES256_GCM,data:PqBlOe2d55BAQFBvMA==,iv:sRkf+nCPGSGuc4qi2cGig6zpsiw8i7vWzrRUVjMCqJY=,tag:73rG7oYWzXwkL5+68/j+bQ==,type:str]
                      value: ENC[AES256_GCM,data:WkDFBzysgUCoKxavIQQ2sg==,iv:E3r50fBZ6UrPKx1jyBQNmgeDwi2YJZ1xHTn7M+gnwOk=,tag:RRShatXC9V7Juat9+X79KA==,type:str]
                    - name: ENC[AES256_GCM,data:y5Z7zfWCNKRDn7/xsP9q,iv:CxTFHFzf1X2SPUDGK/z2wuAFKnYwBGBsnI/ZNHfwoNs=,tag:qf+RL3iZn53sp6tDoZ8a0Q==,type:str]
                      value: ENC[AES256_GCM,data:Du4q,iv:qz70foCAwH9mHo08iBg8yacVjfI3qM1GwiWmxoUAWf8=,tag:hv7/7CxqSfktQ7e+fnNkGQ==,type:str]
                    - name: ENC[AES256_GCM,data:B/AAMGJO/w==,iv:4S2HLXwKh4NA+5FCoD7b1ZzjeLNbQqTRuN4nE2o+MFo=,tag:HJlK5UUaxAAPcs8iwdMmzw==,type:str]
                      value: ENC[AES256_GCM,data:eSl3/az4Rh7jWFEAV+pCURcd7L22YunlbUJ/3S8xD7/bR8pajTqnN4Vd9zr/xw54rMU6,iv:PJ7qSxPuo2hax5RYJsilAnSrAt913FLUC7N+Czh8PvE=,tag:nTEfQNDoO8oVHw0Hf/VPHQ==,type:str]
                    - name: ENC[AES256_GCM,data:rzPZJVLa/A==,iv:3rKhoh16JVjsUbcd5NhIeNZdw0aWI7WfjePhZo7vrT8=,tag:KYJ0izPpyUG+GIVa9ijHyA==,type:str]
                      value: ENC[AES256_GCM,data:bsZPsnD3EseNgQ==,iv:eo1XIjRTOyApXT1MGq+UrK5nLAnKK3kkS22hsbaD1AI=,tag:6TI7Vpj2P3zBOLZcwPlvXQ==,type:str]
                    - name: ENC[AES256_GCM,data:luJwF4gsfXCetSckrmcNCHKKCVA=,iv:NqpavbcxaqD8z9eHmcporKJCO3mtDjJomQGBOlLtgOc=,tag:vy0WeOGXN2D6pbxKBwoV1w==,type:str]
                      value: ENC[AES256_GCM,data:t6WYLQI=,iv:0//giBTFHPdabgKOMCl1FWFfuQ3pS2zD43biJG2Iats=,tag:EsLyQ06i6mubX+VP5dMO4g==,type:str]
                    - name: ENC[AES256_GCM,data:JPlICoLh/LUw2mSW,iv:yZgV4OuFNGxbxEIs3HKjfWrKgjGk8n8aO462M9UAoTo=,tag:mpjej0B6wURglU5473m6rA==,type:str]
                      value: ENC[AES256_GCM,data:d1pLPbY=,iv:sfHhqSAJclGF0nEEecleG1v8Ei3K9JcNfHlviHOgS/w=,tag:6XBusCg6qnXRHhF92Ggf0Q==,type:str]
                    - name: ENC[AES256_GCM,data:hR2LMqTRjL5t5xRQekw=,iv:FNYdvQMJguUVj/YH1Q3mEbr9gwPN8NzS9JNujGGL+OE=,tag:SaOm76Je5FyqPlU8c9VNcg==,type:str]
                      value: ENC[AES256_GCM,data:d1pLPbY=,iv:sfHhqSAJclGF0nEEecleG1v8Ei3K9JcNfHlviHOgS/w=,tag:6XBusCg6qnXRHhF92Ggf0Q==,type:str]
                    - name: ENC[AES256_GCM,data:hgZVvG97cq4waAiT,iv:wfKYwYMRgtE/YHAXo5Xd/3tVwwCCFbYEiQRI4eI3npE=,tag:KqvNJavQKvbCEkSeRjlJvg==,type:str]
                      value: ENC[AES256_GCM,data:d1pLPbY=,iv:sfHhqSAJclGF0nEEecleG1v8Ei3K9JcNfHlviHOgS/w=,tag:6XBusCg6qnXRHhF92Ggf0Q==,type:str]
                    - name: ENC[AES256_GCM,data:7uMWaxw0QtUmoA==,iv:0MTfUghlVkCcX81vS34iiK2WCsJ1BA8KYzwvi/056Hw=,tag:hSPNdpColJvyBu7Fk2fRUg==,type:str]
                      value: ENC[AES256_GCM,data:uPhPtM5+8cxbguahYBtFpr2IEzuNmnUia9u/Khk10aF1hHs8mOUafOfBUZKDkx69pqOWEi/1ig7Q/IYfIUSoWOmmvg==,iv:HK5F5fbEFD1n7v0i/uorrx/sme1Fh6U47EipIjYOJN4=,tag:EjywSxtlFb+8xs5YZzMLkA==,type:str]
                    - name: ENC[AES256_GCM,data:c35TciWbWE0EpmCRoA==,iv:TkvWPihPTIKXmZbxn/QC7dep95bOqHSPIokMOMiS5tI=,tag:c+UHDW2HzRLn+NxPQqBhNw==,type:str]
                      value: ENC[AES256_GCM,data:TOmkMm0=,iv:tg3keBapfuAXh78lamfiN2lGAIA36u2giO6mDy0R34I=,tag:dsgRDz7/kvPofWs1WWbExg==,type:str]
                    - name: ENC[AES256_GCM,data:nQFIh0sQ/yGh0/E=,iv:RRmAsaSLzgQW1HKobjvOL3i1WncSjjp3LqN7ebkyvM4=,tag:v87IcecTLwSdb1/Kfgf3rQ==,type:str]
                      value: ENC[AES256_GCM,data:usrKG+Gr7FM7VIAKpfGw2gKfdMWe+Zw/zSR+Kk9Ic+8=,iv:cRlNHXGHP08UxZt1IVhcEejc5Hq1w6jTb35AO4pHhlQ=,tag:TGTltr1zoxhYWq/sbRCyow==,type:str]
                    - name: ENC[AES256_GCM,data:lUtEBS3DzQDS81I=,iv:IgFGVMMwQDvbe18QXlxI8yLMYmIQ4AR92nIZeXWYOUg=,tag:ihs5VLwelErKnOWvLsanJw==,type:str]
                      value: ENC[AES256_GCM,data:HLHUeDjAGKweGnPdwtLqNFU=,iv:e4bZeRDr0CPi1nZ0wi1O2xzvcYvqksjDrXfEHDNis8g=,tag:d0mzO97bAlRp4266BQn8Ww==,type:str]
                    - name: ENC[AES256_GCM,data:/b9vXCkPYQ==,iv:vjK8QR27dSHgRuL9toNS4vVDEyt11ccoSc8KQyrH2oc=,tag:VlnWB1gNZMMBE0zrKBEoBg==,type:str]
                      value: ENC[AES256_GCM,data:rSWSe2eNWS5y5xGu1zlYWLmXpQbxzpBhanjiqRIxdC3ZU+offnbPQbvg5fhCwB/d9g==,iv:WNMo/vrQn5PYLyvg9tn0sLG2GHkWs+GuQTMFhjRC+JY=,tag:k6sgdLLpf5JhGYUI69s9rw==,type:str]
                    - name: ENC[AES256_GCM,data:XuYqlY10grEEIQUz6vNh,iv:CGZB3eZOHtKVN6jGtBLY0ZTigOyTy8kQsSrAh8nkzbM=,tag:M9Rn6rw6HjZ3vmjH2hNFrQ==,type:str]
                      value: ENC[AES256_GCM,data:Ag==,iv:u/6T1ifIjOqViTW3sEkeQH6i5jT8UuS644utPV/U2EM=,tag:Sy5HdKTsG04DHhOJmiuKww==,type:str]
                      #ENC[AES256_GCM,data:Kg+8p1c2n3+eVZqlkVOn7owM9RZNMd2dY1wscoqyrphWzGg4pdU=,iv:qy3V4a2F1twcr83E1vevVytXbWFUi7XIXnAa/ofUePs=,tag:F6JtbXYnRnFAovLZR2bY/Q==,type:comment]
                    - name: ENC[AES256_GCM,data:4lXWO2X4y86COij95kU+mko=,iv:8psGXKgVm1M51G9GTe1RtW1doCQfx76OdC3uMk2MIIM=,tag:bvU67HxO/RY/WhoagffRtw==,type:str]
                      value: ENC[AES256_GCM,data:27M=,iv:lqpSghcUgfY3ssW7z/+q7LAA+LmR3WLNAx173UAHKns=,tag:yf5WJ2iCRhbdshBoDBhqdQ==,type:str]
                      #ENC[AES256_GCM,data:wb72pXh+icNzJUSQjR8aeA4tdpQsYNL9,iv:lbo3DApgA41CY7HjS2VeyEO0kptbF31mNp1MDUjaHkw=,tag:kssLiSw5kdRIEAra2gFNiA==,type:comment]
                    - name: ENC[AES256_GCM,data:fOKaykEZLJqRTep0GOvnpJzk,iv:np2wU3K3PE44vN2u5tQ1YJ/ndCvYUYh01UBA8q65JT0=,tag:9d/jOwXlF0nDkMtuWfeIVw==,type:str]
                      value: ENC[AES256_GCM,data:engbSmjlnjo7UITd,iv:5Uyo6EqmBdUYOFbkkdCZYq6c8sjVAdeUNiJvVE+VlwI=,tag:Jg6iE7xPdd6Vdd6oad0wvA==,type:str]
                    - name: ENC[AES256_GCM,data:LrIKjTFQTvpWSlQ3qmD3US4=,iv:yx7FNB8EU+dmJu4TYQgQ9WcJQMC+fiScoejmbjY1LEI=,tag:VvNyNEgXSk+7eXYfuyVlHA==,type:str]
                      value: ENC[AES256_GCM,data:dN0Sht58oweqlhSgAuQ4AT4oSQO62flXHZK+T5qsrvb8oYvWx0gFZA==,iv:YCz6ZtcvgYquQPTsSvN+H4tdntH7hJtHRofk3SuEQCk=,tag:LTC2rliIOeVt3DFd3ETVLw==,type:str]
                    - name: ENC[AES256_GCM,data:T581Vjf30FP7RUjSbobdAjQDLOdQ,iv:pe6V/4ZVsibELytYS4sAutfkN9TWOtRepAJML3Eokq8=,tag:xGYZtWh/t1rpX/kb9qL3rg==,type:str]
                      value: ENC[AES256_GCM,data:cPinHIE/0RKBZK0WKPif8LdE2y+ocRgqeZJ0IYzpJ1V91ejE8epAGHA16kI=,iv:udAPC+iRpaPbmg1/PQfr1L0GB7OFiHlnTDaxelMSShY=,tag:/ESyQAvVg1HQSs1PEGkpJQ==,type:str]
                    - name: ENC[AES256_GCM,data:ubyvxPKiPn5JZj9yGkMUYEwO,iv:5EajTwzh4cEP4I1G/5JQ83CEkm+/GhkJAY9CZt6IRcs=,tag:4ebmzJ7g+2qjmBnGKVtkqQ==,type:str]
                      value: ENC[AES256_GCM,data:+yaGAtFjey977npnx3hkEijzBw==,iv:h44OoMSrPjkLcmDiHediU3DV+1rLTg0D1je9N+T3OPw=,tag:Iz7dPoJOOzb/RMpKhvK1sQ==,type:str]
                    - name: ENC[AES256_GCM,data:G1CGac4r0pxKJbhz,iv:Dch7BPAVGVYMijCHCILUFE5nmZGs96hxYlB5F4aVTgc=,tag:1MH8XUEVypaXOuE7nhjf9g==,type:str]
                      value: ENC[AES256_GCM,data:Ty922qeYOKuJQki9vNAOyAcCpTZVvy0nxZxFhPJ8Kbd5iRQLkYmXZcOFjmfCreRf0LVUCa/fh1dMnlQLisdwg0Reuiu56Q==,iv:Ah6N8jeiOSu+lLygf8g8eNOHmjsmj3gqoGszOivg2CQ=,tag:yQcsVzSO2nSTLzKDbilKVQ==,type:str]
                    - name: ENC[AES256_GCM,data:aGiZBDXd4rT5LhFG/fyb500ancsU/4PnwQI5,iv:+wzKpEy3KZEsx4iW/jKU4c1sSPkxBAQ6fKIzEovWCKM=,tag:IG0vE4Mm4lmnTOdG/+k5Ag==,type:str]
                      value: ENC[AES256_GCM,data:YEsTTg==,iv:5255AYhBuWw/DnlwOd4xoLtssdp7v3+nbrH8KVRgcTM=,tag:y9TV88i0tI9zguoyhSydRA==,type:str]
                      #ENC[AES256_GCM,data:at+Flbops/vCs2DDhQ10F1/XfuJoJR89BytjtYPvdaLeM8c=,iv:/Zt6/FgCBnKHl6AH0w5rfQ0INldIrKAn9Z2LaQ/lvxg=,tag:BKH5V/7IhAzwNIEOCdD35Q==,type:comment]
                      #ENC[AES256_GCM,data:+mrZaMQCqCIakX7SYjGUA7QiP6V/docUKhZP076q++YGQG3L7g==,iv:QGc8nI01BEPYTiXzf16vAEvxu7qLJMtqX6K9weO5yqE=,tag:uLN7sQFNs2fPSwGodiHh9A==,type:comment]
service:
    main:
        controller: main
        ports:
            http:
                port: 80
            https:
                port: 443
ingress:
    main:
        enabled: true
        annotations:
            external-dns.alpha.kubernetes.io/cloudflare-proxied: ENC[AES256_GCM,data:NH9A2Q==,iv:3aAs5Tgd2GlMQW6bOiUgxIdv7odtqiJbbQGlXiDa0Qg=,tag:oxNr+b3deL0SJ+GUpj226g==,type:str]
            external-dns.alpha.kubernetes.io/enabled: ENC[AES256_GCM,data:+7HVdg==,iv:o98zHOkiYlWrDQOSTnQgDPXuoWcluxZDh4LpPLOqO9M=,tag:scuwmrhAnHPiTePMuLkorw==,type:str]
            kubernetes.io/ingress.class: ENC[AES256_GCM,data:OHiQuvvFww==,iv:IoWKxxZxxnfU5LK4wcTjXZbQ/I7XaMX92D97TFKch+E=,tag:iHt0dU2X5DhaQ7m2RIg/AA==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:5vTqQAw7L6Vn/+39l10BFPXaL7EjAN3Y,iv:1xyU17QSGLv3MjR9a4gnSVrCgskU8BNNsGjC0idrVcE=,tag:V4uXmsAX7SpXvYpOqRnHnA==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:1g==,iv:uHVc0JKI7v91Y3g02jHkpCimx57aHUaXJHmOuKOCML0=,tag:Y5GtxFr4TBenovAE8xpYSQ==,type:str]
                  pathType: ENC[AES256_GCM,data:271buWu1,iv:uKG48AshGmLgFy1p46nXqbWMNU1AjCxtjO6d2zp+j6o=,tag:erwcPbmA2z8/2nqnWDDHCA==,type:str]
                  service:
                    identifier: ENC[AES256_GCM,data:3wNpoA==,iv:DEf9hWCm5NDHLvz3s4lHMiCmblr+BbLHXJ8uXaCN624=,tag:vAYoPpsQ/vtxPIcz52FZTQ==,type:str]
                    port: ENC[AES256_GCM,data:BgSwSQ==,iv:SmNrMwOu8Fo4HwIiKg9LOKJFXT8xf/ppbcV9SnAyKAU=,tag:4Vwlzl5WKYh+sOEaqH+hFA==,type:str]
persistence:
    data:
        enabled: ENC[AES256_GCM,data:20L/rQ==,iv:jpSH5+rSH1ezMcBC+0OtHqMC04rX2J9drIJO2BichvA=,tag:17Qpe6IZgzc2ePjpnI+2OQ==,type:bool]
        size: ENC[AES256_GCM,data:6r3Zbw==,iv:zer2ch5X21dJcQaZm/sQVyB5RPEyieYMe8Ry/KJO//8=,tag:rQOXZtlQtLNc9Din/ZTO6A==,type:str]
        type: ENC[AES256_GCM,data:HCRmH3n5NhnLqzuhTT3XSgO/5bTj,iv:LRuKRrg0juVYShvIJQrgE2aTRqJYotsAX/yJHV+2YvE=,tag:SIw6kM544X46vT613OcZHg==,type:str]
        storageClass: ENC[AES256_GCM,data:IZTmUDjy1k4yHA==,iv:69nhZGe9LSlfm55IVvKnFsYhmwhzfKlfK61Us5HAfgo=,tag:QfC3ihHVmguqJtKvnw456A==,type:str]
        accessMode: ENC[AES256_GCM,data:8FLNpIA4m6aeD4jaVQ==,iv:T9JrodnHSoML8Z1PwLCoqkZnpG5sWo9sfX1YD+oQBJ4=,tag:ATLaT8K+61l2eqlGODHnrA==,type:str]
        globalMounts:
            - path: ENC[AES256_GCM,data:rLW6vas/ayN7,iv:BaRgUP8liDEYInVJpi+cAnnOOAUfvH6kq79LHyqobtU=,tag:oAFQX7Lsgujxwg2SYoTAiQ==,type:str]
    logs:
        enabled: true
        type: emptyDir
        globalMounts:
            - path: /app/storage/logs
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u9xhf474aapqtea5myafnd6asdwv8nldgu2gefxcvdl2869zddwspsdqu6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWldlNW1malAycWRVUWNm
            WTBFU1dvTU9UQkwvUitqVllxWE1pa1A2STM4ClVrZDdVUjdPTStNbFAzb3F1dWVL
            WUUzaGEyZlp3NUErOEtlWkxTeGd1QnMKLS0tIHdGOUlRbGNrdUp6QnRKa1gzdXJ0
            SWdkeGJubUJGajRtc1ZxbUJYKy9xUXMK1sT8dwj3+IMka4sGa+IVnjwNwHIDZu01
            oKzvca1WcazQ4E4KaHYA1VdurbowY6ZeJHx+0fpNUlULxSFFQ3RlzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T18:23:45Z"
    mac: ENC[AES256_GCM,data:w4iksDCt71R3rju/WRpYeVGDjWV/0VZODNfjUMBfWGxc/0YxmNTLfnAD0fullwiEJRGoHWfr+G/eD1E7xp74heBNDG20UzH/wrmoWgyzYKf292ymhiONh/4V+IiXa830RScQfRR1TbmkWXNiMPgakYWXPpX9t6CMb28znyGnmUs=,iv:FP8bZy1PZ0rY75Qz67DQ/70ocgilvVm5Ie9y9mthfKY=,tag:INmHubeLlUttXZhpc8fkmw==,type:str]
    pgp: []
    encrypted_regex: ^(id|secret|password|extraEnv|env|encryption_key|data|stringData|host|db|influxdb_v2|dendrite_config|wildcardHost|clientId|clientSecret)|(external-dns.alpha.kubernetes.io.*|kubernetes.io/ingress.class.*)$
    version: 3.9.1
