apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: directus
  namespace: development
spec:
  interval: 20m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-app-template-repo
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: directus-values
