apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./tailscale/repository.yaml
  - ./tailscale/release.yaml
  - ./tailscale/connections/connector.yaml
  - ./tailscale/connections/sr-in-cluster.yaml
  - ./tailscale/connections/sr-to-internet.yaml
  - ./telegraf/repository.yaml
  - ./telegraf/release.yaml
namespace: management-stack
configurations:
  - kustomizeconfig.yaml
secretGenerator:
  - name: tailscale-values
    files:
      - values.yaml=./tailscale/values.sops.yaml
  - name: telegraf-values
    files:
      - values.yaml=./telegraf/values.sops.yaml
