apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-metrics-repo
  namespace: management-stack
spec:
  interval: 36h
  url: "https://kubernetes-sigs.github.io/metrics-server/"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-metrics
  namespace: management-stack
spec:
  interval: 24h
  chart:
    spec:
      chart: metrics-server
      version: 3.12.2
      sourceRef:
        kind: HelmRepository
        name: k8s-metrics-repo
        namespace: management-stack
