---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik-repo
  namespace: connectivity-stack
spec:
  interval: 24h
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: connectivity-stack
spec:
  interval: 24h
  chart:
    spec:
      chart: traefik
      version: 35.2.0
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: connectivity-stack
  valuesFrom:
    - kind: Secret
      name: traefik-values
