apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nocodb
  namespace: development
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-app-template-repo
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: nocodb-values
