architecture: standalone

auth:
  enabled: false
master:
  persistence:
    enabled: true
    storageClass: "nfs-client"
    accessModes:
      - ReadWriteOnce
    size: 100Mi
  service:
    annotations:
      app: rsshub-redis
