apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pterodactyl-redis
  namespace: integration-stack
spec:
  interval: 10m
  chart:
    spec:
      chart: redis
      version: 20.13.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: pterodactyl-redis-values
