---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-repo
  namespace: connectivity-stack
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: connectivity-stack
spec:
  interval: 24h
  chart:
    spec:
      chart: cert-manager
      version: v1.17.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repo
        namespace: connectivity-stack
  valuesFrom:
    - kind: Secret
      name: cert-manager-values