apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: management-stack
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.64.2
      sourceRef:
        kind: HelmRepository
        name: tailscale-repo
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: tailscale-values
