apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: management-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      version: 1.82.0
      sourceRef:
        kind: HelmRepository
        name: tailscale-repo
        namespace: management-stack
  valuesFrom:
    - kind: Secret
      name: tailscale-values
