apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n-release
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: 1.0.6
      sourceRef:
        kind: HelmRepository
        name: n8n-repo
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: n8n-values
