apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./rsshub/release.yaml
  - ./rsshub/redis/release.yaml
namespace: integration-stack
commonAnnotations:
  app: rsshub
configurations:
  - kustomizeconfig.yaml
secretGenerator:
  - name: rsshub-values
    files:
      - values.yaml=./rsshub/values.sops.yaml
  - name: rsshub-redis-values
    files:
      - values.yaml=./rsshub/redis/values.sops.yaml
