apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: github
  address: https://github.com/fdelucchijr/flux-gitops
  secretRef:
    name: github
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: global-alert
  namespace: flux-system
spec:
  providerRef:
    name: flux-system
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
      namespace: "*"
    - kind: Kustomization
      name: "*"
      namespace: "*"
    - kind: HelmRelease
      name: "*"
      namespace: "*"
